blank_issues_enabled: false
contact_links:
  - name: Lunatone DALI-2 IoT Gateway Documentation
    url: https://www.lunatone.com/wp-content/uploads/2021/08/89453886_DALI2_IOT_API_Dokumentation_EN_M0023.pdf
    about: Official Lunatone DALI-2 IoT Gateway API documentation
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Ask questions and get support from the Home Assistant community
